# application.properties
spring.application.name=DreamZone

# MongoDB
spring.data.mongodb.uri=mongodb+srv://dreamzone:dreamzone123@dreamzone.r19nhcf.mongodb.net/dreamzone?appName=DreamZone
spring.data.mongodb.database=dreamzone

# Thymeleaf
spring.thymeleaf.cache=false

# Subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080