# application.properties
spring.application.name=DreamZone

# MongoDB
spring.data.mongodb.uri=mongodb+srv://dreamzone:dreamzone123@dreamzone.r19nhcf.mongodb.net/dreamzone?appName=DreamZone
spring.data.mongodb.database=dreamzone

# Thymeleaf
spring.thymeleaf.cache=false

# Subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080
# Correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dreamzzone026@gmail.com
spring.mail.password=gtil nxby adxm arim
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
